name: ESLint

on:
  push:
    branches:
      - main
  pull_request: # Trigger on PRs to any branch
    branches:
      - '*'

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify the Node.js version you are using

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
